version: '3.8'
services:

  endpoint:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      localstack:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID="test"
      - AWS_SECRET_ACCESS_KEY="test"
      - AWS_REGION=us-west-2

  localstack:
    #image: localstack/localstack:2.0
    image: localstack/localstack:latest@sha256:2e4e6c1c4f19c1832059e64dfad731b627c51be42caa9402c2e3dd7dff686fbb
    ports:
      - "4566:4566"
    environment:
      - DEFAULT_REGION=us-west-2
      - DEBUG=true
    healthcheck:
      test: curl --fail http://localhost:4566 || exit 1
      interval: 2s
      timeout: 10s
      retries: 10

